/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: (typeof import('./components/layouts/BaseHeader.vue'))['default'];
    BaseSide: (typeof import('./components/layouts/BaseSide.vue'))['default'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElCard: (typeof import('element-plus/es'))['ElCard'];
    ElCascader: (typeof import('element-plus/es'))['ElCascader'];
    ElCol: (typeof import('element-plus/es'))['ElCol'];
    ElCollapse: (typeof import('element-plus/es'))['ElCollapse'];
    ElCollapseItem: (typeof import('element-plus/es'))['ElCollapseItem'];
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker'];
    ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions'];
    ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem'];
    ElDialog: (typeof import('element-plus/es'))['ElDialog'];
    ElEmpty: (typeof import('element-plus/es'))['ElEmpty'];
    ElForm: (typeof import('element-plus/es'))['ElForm'];
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElInputNumber: (typeof import('element-plus/es'))['ElInputNumber'];
    ElMenu: (typeof import('element-plus/es'))['ElMenu'];
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
    ElOption: (typeof import('element-plus/es'))['ElOption'];
    ElPopover: (typeof import('element-plus/es'))['ElPopover'];
    ElRow: (typeof import('element-plus/es'))['ElRow'];
    ElSelect: (typeof import('element-plus/es'))['ElSelect'];
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
    ElTable: (typeof import('element-plus/es'))['ElTable'];
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane'];
    ElTabs: (typeof import('element-plus/es'))['ElTabs'];
    ElTag: (typeof import('element-plus/es'))['ElTag'];
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default'];
    Logos: (typeof import('./components/Logos.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import('element-plus/es'))['ElLoadingDirective'];
  }
}
